LibrarySystem/LibrarySystem/urls.py
from django.contrib import admin
from django.urls import path
from library.views import LoginAPI, RegisterAPI, home, signin, signout, book_list, getbook, edit, addbook, delete, book_details
from rest_framework.urlpatterns import format_suffix_patterns
from knox import views as knox_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/login/', LoginAPI.as_view(), name='login'),
    path('api/logout/', knox_views.LogoutView.as_view(), name='logout'),
    path('api/logoutall/', knox_views.LogoutAllView.as_view(), name='logoutall'),
    path('api/register/', RegisterAPI.as_view(), name='register'),
    path('api/books/', book_list, name='books'),
    path('api/books/<int:id>', book_details),
    path('', home, name='home'),
    path('addbook/', addbook, name='addbook'),
    path('getbook/', getbook, name='getbook'),
    path('edit/<int:pk>/', edit, name='edit'),
    path('delete/<int:pk>/', delete, name='delete'), 
    path('login/', signin, name='login'),
    path('logout/', signout, name='logout'), 
]   
urlpatterns=format_suffix_patterns(urlpatterns)

LibrarySystem/library/models.py
from django.db import models
# Create your models here

class Book(models.Model):
    title=models.CharField(max_length=40, null=False)
    author=models.CharField(max_length=100, default=' ')
    publisher=models.CharField(max_length=100, default=' ')
    published=models.DateTimeField(auto_now_add=True)
    summary=models.TextField(max_length=400)

    def __str__(self):
        return self.title

LibrarySystem/library/forms.py
from django.forms import ModelForm
from .models import Book

class BookForm(ModelForm):
    class Meta:
        model=Book
        fields='__all__'

LibrarySystem/library/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from library.serializers import BookSerializer
from rest_framework.decorators import api_view
from rest_framework import status
from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework import generics, permissions
from knox.models import AuthToken
from .serializers import UserSerializer, RegisterSerializer
from rest_framework.authtoken.serializers import AuthTokenSerializer
from knox.views import LoginView as KnoxLoginView
from django.contrib.auth.decorators import login_required
from .models import Book
from .forms import BookForm

def home(request):
    return render(request, 'home.html')

class LoginAPI(KnoxLoginView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request, format=None):
        serializer = AuthTokenSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        login(request, user)
        return super(LoginAPI, self).post(request, format=None)

class RegisterAPI(generics.GenericAPIView):
    serializer_class = RegisterSerializer

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        return Response({
        "user": UserSerializer(user, context=self.get_serializer_context()).data,
        "token": AuthToken.objects.create(user)[1]
        })  

@api_view(['GET','POST'])
def book_list(request, format=None):
    if request.method=='GET':
        books=Book.objects.all()
        serializer=BookSerializer(books, many=True)
        return JsonResponse(serializer.data, safe=False)
    if request.method=='POST':
        BookSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)

@api_view(['GET','POST','DELETE'])
def book_details(request, id, format=None):
    try:
        book=Book.objects.get(pk=id)
    except Book.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)
    if request.method=='GET':
        serializer=BookSerializer(book)
        return Response(serializer.data)
    elif request.method=='POST':
        serializer=BookSerializer(book, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    elif request.method=='DELETE':
        book.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

def signin(request):
    if request.user.is_authenticated==False:
        if(request.method=="POST"):
            username=request.POST['username']
            password=request.POST['password']
            user=authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.success(request, ('There was error.'))
                return redirect('login')

        else:
            return render(request,'login.html')
    else:
        return redirect('/')

def signout(request):
    logout(request)
    return redirect('/')
    
def addbook(request):
    if request.user.is_authenticated:
        fm=BookForm(request.POST)
        if fm.is_valid():
            form=fm.save(commit=False)
            form.save()
            messages.success(request, ('Added'))
            return redirect('/')
        else:
            return render(request, 'addbook.html', {'fm':fm})

    return render(request, 'addbook.html')

def getbook(request):
    book=Book.objects.all()
    return render(request, 'getbook.html', {'book':book})
    
@login_required
def edit(request, pk):
    book=Book.objects.get(id=pk)
    if request.user.is_authenticated:
        fm=BookForm(instance=book)
        if request.method=='POST':
            fm=BookForm(request.POST, instance=book)
            if fm.is_valid():
                form=fm.save(commit=False)
                fm.save()
                return redirect('/')

        return render(request, 'edit.html', {'fm':fm})
    else:
        return redirect('/')

@login_required
def delete(request, pk):
    book=Book.objects.get(id=pk)
    if request.user.is_authenticated:
        book.delete()
        return redirect('getbook')
    else:
        return redirect('/')


LibrarySystem/library/templates/addbook.html
{% extends 'index.html' %}
{% block head %}
    <title>Home</title>
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h3>Username:{{user}}</h3>
        {% if messages %}
            {% for message in messages %}
                <h3>{{ message }}</h3>
            {% endfor %}
        {% endif %}
        <form action="" method="POST">
            {% csrf_token %}
            <p>
                <label for="id_title">Title:</label>
                {{fm.title}}
            </p>
            <p>
                <label for="id_author">Author:</label>
                {{fm.author}}
            </p>
            <p>
                <label for="id_publisher">Publisher:</label>
                {{fm.publisher}}
            </p>
            <p>
                <label for="id_summary">Summary:</label>
                {{fm.summary}}
            </p>
            <input type="submit" value="ADD">
        </form>
    {% endif %}
    <style>
        #cont {
            width: 150px;
            text-align: center;
        }
        th, td {
            background-color: #d5d1f5;
            padding: 10px;
            width: 50px;
        }
        table {
            border: 1px solid black;
        }
        #cpass {
            float: right;
        }
        #but {
            text-decoration: none;
            padding: 5px 10px 5px 10px;
            border-radius: 3px;
            background-color: brown;
            color: azure;
            margin: 5px 15px 5px 15px;
        }
        #but:hover {
            background-color: rgb(170, 67, 67)
        }
        label {
            display: inline-table;
            width: 120px;
            font-weight: bold;
            font-size: 1.05rem;
        }
        input[type=submit] {
            width: 75px;
            height: 30px;
            border: 0;
            border-radius: 3px;
            background-color: rgb(69, 69, 121);
            color: white;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=submit]:hover {
            background-color: rgb(88, 88, 150);
        }

        body {
            display: grid;
            justify-content: center;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=text] {
            outline: none;
            width: 200px;
            height: 23px;
            border-radius: 3px;
            border: 1px solid black;
            font-size: 1.05rem;
            font-family: 'Courier New', Courier, monospace;
        }
        h4 {
            text-align: center;
        }
        @media screen and (max-width: 500px) {
            body {
                font-size: 0.92rem;
            }
            table, form {
                width: 100%;
                margin-right: 5px; 
            }
            th, td {
                padding: 5px 4px 5px 4px;
                margin: 0;
            }
            #but {
                padding: 4px 5px 4px 5px;
                margin: 0 5px 0 5px;
                border-radius: 2px;
            }
        }
        @media screen and (max-width: 325px) {
            body, label {
                font-size: 0.8rem;
            }
            table, form {
                width: 100%;
                margin-top: 0px;
            }
            th, td {
                padding: 3px 2px 3px 2px;
                margin: 0;
            }
            #but {
                padding: 3px 3px 3px 3px;
                margin: 0 5px 0 5px;
                border-radius: 2px;
            }
            input[type=submit] {
                font-size: 0.8rem;
                width: 50px;
                height: 28px;
            }
            input[type=text] {
                width: 150px;
            }
            label {
                width: 80px;
            }
        }
    </style>
{% endblock %}

LibrarySystem/library/templates/changepass.html
{% extends 'index.html' %}
{% block head %}
    <title>Change Password</title>
{% endblock %}
{% block content %}
    <div>
        <h1>Change Password</h1>
        {% if messages %}
            {% for message in messages %}
                <h4>{{ message }}</h4>
            {% endfor %}
        {% endif %}
        <form method="POST" action="">
            {% csrf_token %}
            
            <label>Old Password</label>
            {{fm.old_password}}<br>
            <label>New Password</label>
            {{fm.new_password1}}<br>
            <label>Confirm Password</label>
            {{fm.new_password2}}<br>
            <input type="submit" value="Change">
        </form><br>
        <p>Go Back? <a href="{% url 'home' %}">Cancel</a>.</p>
    </div>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Courier New', Courier, monospace;
        }
        div {
            border: 2px solid black;
            border-radius: 5px;
            width: 530px;
            height: auto;
            position: absolute;
            left: 50%;
            transform: translate(-50%, 30%);
        }
        h1 {
            text-align: center;
        }
        p {
            margin-top: 115px;
            margin-left: 40px;
            font-size: 1.05rem;
        }
        h4, form {
            margin-left: 40px;
        }
        input[type=submit] {
            width: 100px;
            height: 30px;
            border: 0;
            border-radius: 3px;
            background-color: rgb(69, 69, 121);
            color: white;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=submit]:hover {
            background-color: rgb(88, 88, 150);
        }
        label{
            display: block;
            float: left;
            width: 230px;
            font-size: 20px;
            margin-bottom: 20px;
        }
        input {
            display: block;
            float: left;
        }
        input[type="password"] {
            outline: none;
            width: 230px;
            height: 25px;
            margin-bottom: 20px;
            border-top: 0;
            border-left:0;
            border-right: 0;
            background: #eee;
            border-radius: 5px;
            font-family: 'Courier New', Courier, monospace;
            font-size: 1.05rem;
        }
        @media screen and (max-width: 460px) {
            body{
                font-size: 1rem;
            }
            h1 {
                font-size: 1.5rem;
            }
            div {
                width: 99%;
            }
            label {
                width: 45%;
                height: 22px;
                font-size: 1rem;
            }
            input[type="password"] {
                width: 45%;
                height: 22px;
                margin-bottom: 18px;
            }
            form {
                margin-left: 20px;
            }
            p {
                margin-top: 100px;
                margin-left: 20px;
            }
        }
        @media screen and (max-width: 340px) {
            body {
                font-size: 1rem;
            }
            h1 {
                font-size: 1.3rem;
                margin-top: 10px;
            }
            div {
                width: 99%;
            }
            input[type="password"] {
                font-size: 0.85rem;
                width: 50%;
                height: 20px;
                margin-bottom: 22px;
            }
            label {
                margin-bottom: 25px;
                width: 45%;
                height: 20px;
                font-size: 0.85rem;
            }
            input[type="submit"] {
                width: 75px;
                height: 25px;
                font-size: 0.9rem;
                border-radius: 2px;
            }
            form {
                margin-left: 15px;
            }
            p {
                margin-top: 100px;
                margin-left: 15px;
                font-size: 0.9rem;
                margin-bottom: 10px;
            }
        }
    </style>
{% endblock %}

LibrarySystem/library/templates/edit.html
{% extends 'index.html' %}
{% block head %}
    <title>Edit</title>
{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <p>
            <label for="id_title">Title:</label>
            {{fm.title}}
        </p>
        <p>
            <label for="id_complted">Author:</label>
            {{fm.author}}
        </p>
        <p>
            <label for="id_title">Summary:</label>
            {{fm.summary}}
        </p>
        <p>
            <label for="id_complted">Story:</label>
            {{fm.story}}
        </p>
        <input type="submit" value="Update">
    </form>
    <style>
        body {
            display: grid;
            justify-content: center;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=text] {
            outline: none;
            width: 200px;
            height: 23px;
            border-radius: 3px;
            border: 1px solid black;
            font-size: 1.05rem;
            font-family: 'Courier New', Courier, monospace;
        }
        label {
            display: inline-table;
            width: 120px;
            font-weight: bold;
            font-size: 1.05rem;
        }
        input[type=submit] {
            width: 75px;
            height: 30px;
            border: 0;
            border-radius: 3px;
            background-color: rgb(69, 69, 121);
            color: white;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
        
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=submit]:hover {
            background-color: rgb(88, 88, 150);
        }
        @media screen and (max-width: 460px) {
            label {
                font-size: 1rem;
            }
            input[type="submit"] {
                font-size: 1rem;
                width: 80px;
                height: 25px;
                border-radius: 2px;
            }
        }
        @media screen and (max-width: 340px) {
            label {
                font-size: 0.85rem;
            }
            input[type="submit"] {
                font-size: 0.85rem;
                width: 70px;
                height: 25px;
                border-radius: 2px;
            }
            input[type="text"] {
                height: 20px;
            }
        }
    </style>
{% endblock %}

LibrarySystem/library/templates/getbook.html
{% extends 'index.html' %}
{% block head %}
    <title>Home</title>
{% endblock %}
{% block content %}
    <h2>Library</h2>
    {% if user.is_authenticated %}
        {% if book|length > 0 %}
            <table>
                <tr>
                    <th id="cont">Book</th>
                    <th id="crea">Author</th>
                    <th id="cont">Publisher</th>
                    <th id="crea">Publised Date</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                {% for bk in book %}
                    <tr>
                        <td id="cont">{{ bk.title }}</td>
                        <td id="cont">{{ bk.author }}</td>
                        <td id="cont">{{ bk.publisher }}</td>
                        <td id="cont">{{ bk.published.date }}</td>
                        <td><a href="{% url 'edit' bk.id %}"  id="but">Edit</a></td>
                        <td><a href="{% url 'delete' bk.id %}" style="margin-left: 3px;"  id="but">Delete</a></td>
                    </tr>
                {% endfor %}
            </table><br>
        {% else %}
            <h4>There are no Book.</h4>
        {% endif %}
    {% else %}
        {% if book|length > 0 %}
            <table>
                <tr>
                    <th id="cont">Book</th>
                    <th id="crea">Author</th>
                    <th id="cont">Publisher</th>
                    <th id="crea">Published Date</th>
                </tr>
                {% for bk in book %}
                    <tr>
                        <td id="cont">{{ bk.title }}</td>
                        <td id="cont">{{ bk.author }}</td>
                        <td id="cont">{{ bk.publisher }}</td>
                        <td id="cont">{{ bk.published.date }}</td>
                    </tr>
                {% endfor %}
            </table><br>
        {% else %}
            <h4>There are no Book.</h4>
        {% endif %}
    {% endif %}
    <style>
        #cont {
            width: 150px;
            text-align: center;
        }
        th, td {
            background-color: #d5d1f5;
            padding: 10px;
            width: 50px;
        }
        table {
            border: 1px solid black;
        }
        #cpass {
            float: right;
        }
        #but {
            text-decoration: none;
            padding: 5px 10px 5px 10px;
            border-radius: 3px;
            background-color: brown;
            color: azure;
            margin: 5px 15px 5px 15px;
        }
        #but:hover {
            background-color: rgb(170, 67, 67)
        }
        label {
            display: inline-table;
            width: 120px;
            font-weight: bold;
            font-size: 1.05rem;
        }
        input[type=submit] {
            width: 75px;
            height: 30px;
            border: 0;
            border-radius: 3px;
            background-color: rgb(69, 69, 121);
            color: white;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=submit]:hover {
            background-color: rgb(88, 88, 150);
        }

        body {
            display: grid;
            justify-content: center;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=text] {
            outline: none;
            width: 200px;
            height: 23px;
            border-radius: 3px;
            border: 1px solid black;
            font-size: 1.05rem;
            font-family: 'Courier New', Courier, monospace;
        }
        h4 {
            text-align: center;
        }
        @media screen and (max-width: 500px) {
            body {
                font-size: 0.92rem;
            }
            table, form {
                width: 100%;
                margin-right: 5px; 
            }
            th, td {
                padding: 5px 4px 5px 4px;
                margin: 0;
            }
            #but {
                padding: 4px 5px 4px 5px;
                margin: 0 5px 0 5px;
                border-radius: 2px;
            }
        }
        @media screen and (max-width: 325px) {
            body, label {
                font-size: 0.8rem;
            }
            table, form {
                width: 100%;
                margin-top: 0px;
            }
            th, td {
                padding: 3px 2px 3px 2px;
                margin: 0;
            }
            #but {
                padding: 3px 3px 3px 3px;
                margin: 0 5px 0 5px;
                border-radius: 2px;
            }
            input[type=submit] {
                font-size: 0.8rem;
                width: 50px;
                height: 28px;
            }
            input[type=text] {
                width: 150px;
            }
            label {
                width: 80px;
            }
        }
    </style>
{% endblock %}

LibrarySystem/library/templates/home.html
{% extends 'index.html' %}
{% block head %}
    <title>Home</title>
{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <div id="addb"><a href="{% url 'addbook' %}">Add Book</a></div>
        <div id="getb"><a href="{% url 'getbook' %}">Get all the books</a></div>
        <div id="log1"><a href="{% url 'logout' %}">Logout</a></div>
    {% else %}
        <div id="getb"><a href="{% url 'getbook' %}">Student View</a></div>
        <div id="log2"></div><a href="{% url 'login' %}">Admin Login</a></div>
    {% endif %}
    <style>
        body {
            display: grid;
            justify-content: center;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        #addb, #getb, #log1, #log2 {
            font-size: 1.2rem;
            border-radius: 2px;
        }
        a {
            text-decoration: none;
            color: black;
            font-family: 'Courier New', Courier, monospace;
        }
    </style>
{% endblock %}

LibrarySystem/library/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %} {% endblock %}
</head>
<body>
    {% block content %} {% endblock %}
</body>
</html>

LibrarySystem/library/templates/login.html
{% extends 'index.html' %}
{% block head %}
    <title>Login</title>
{% endblock %}
{% block content %}
    <div>
        <h1>LOGIN</h1>
        {% if messages %}
            {% for message in messages %}
                <h4>{{ message }}</h4>
            {% endfor %}
        {% endif %}
        <form method="POST" action="#">
            {% csrf_token %}
            
            <label>Username</label>
            <input type="text" name="username" required><br>
            <label>Password</label>
            <input type="password" name="password" required><br>
            <input type="submit" value="Login">
        </form><br>
    </div>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: 'Courier New', Courier, monospace;
        }
        div {
            border: 2px solid black;
            border-radius: 5px;
            width: 430px;
            height: auto;
            position: absolute;
            left: 50%;
            transform: translate(-50%, 50%);
            padding-bottom: 25px;
        }
        h1 {
            text-align: center;
        }
        h4, form {
            margin-left: 40px;
        }
        input[type=submit] {
            width: 75px;
            height: 30px;
            border: 0;
            border-radius: 3px;
            background-color: rgb(69, 69, 121);
            color: white;
            font-size: 1.05rem;
            letter-spacing: 0.5px;
            font-family: 'Courier New', Courier, monospace;
        }
        input[type=submit]:hover {
            background-color: rgb(88, 88, 150);
        }
        label{
            display: block;
            float: left;
            width: 115px;
            font-size: 20px;
        }
        input {
            display: block;
            float: left;
        }
        input[type="text"], input[type="password"] {
            outline: none;
            width: 230px;
            height: 25px;
            border-top: 0;
            border-left:0;
            border-right: 0;
            margin-bottom: 35px;
            background: #eee;
            border-radius: 5px;
            font-family: 'Courier New', Courier, monospace;
            font-size: 1.05rem;
        }
        @media screen and (max-width: 430px) {
            body, label {
                font-size: 1.05rem;
                width: 32%;
            }
            div {
                width: 99%;
                padding-bottom: 20px;
            }
            input[type="text"], input[type="password"] {
                width: 58%;
                height: 22px;
                margin-bottom: 18px;
            }
            form {
                margin-left: 20px;
            }
        }
        @media screen and (max-width: 330px) {
            body, label {
                font-size: 1rem;
                width: 35%;
            }
            h1 {
                font-size: 1.3rem;
                margin-top: 10px;
            }
            div {
                width: 99%;
                padding-bottom: 20px;
            }
            input[type="text"], input[type="password"] {
                font-size: 0.8rem;
                width: 58%;
                height: 19px;
                margin-bottom: 15px;
            }
            input[type="submit"] {
                width: 75px;
                height: 25px;
                font-size: 0.9rem;
                border-radius: 2px;
            }
            form {
                margin-left: 15px;
            }
        }
    </style>
{% endblock %}